# Generated by Django 2.1.7 on 2019-05-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('contents', models.TextField(max_length=2000, verbose_name='contents')),
                ('pwd', models.CharField(default='', max_length=8, verbose_name='password')),
                ('posted_date', models.DateTimeField(auto_now_add=True, max_length=200, verbose_name='posted_date')),
                ('commented_post', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='title')),
                ('owner_name', models.CharField(default='', max_length=20)),
                ('contents', models.TextField(max_length=200, verbose_name='contents')),
                ('owner_pwd', models.CharField(default='', max_length=8, verbose_name='password')),
                ('posted_date', models.DateTimeField(auto_now_add=True, max_length=200, verbose_name='posted_date')),
                ('image_url', models.URLField(default='', max_length=1000, verbose_name='imageurl')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('is_finish', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='title')),
                ('description', models.TextField(max_length=2000, verbose_name='description')),
                ('section', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('date1', models.IntegerField(default=0)),
                ('date2', models.IntegerField(default=0)),
                ('date3', models.IntegerField(default=0)),
                ('image_booth', models.URLField(default='', max_length=1000, verbose_name='imagebooth')),
            ],
        ),
    ]
