# Generated by Django 2.1.7 on 2019-05-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_finish',
            field=models.IntegerField(default=0),
        ),
    ]
