# Generated by Django 2.1.7 on 2019-05-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivalapp', '0002_post_is_finish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pub',
            name='date',
        ),
        migrations.AddField(
            model_name='pub',
            name='date1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pub',
            name='date2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pub',
            name='date3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pub',
            name='image_booth',
            field=models.URLField(default='', max_length=1000, verbose_name='imagebooth'),
        ),
    ]
